### ISSUE TITLE
Update Vidi's core UI

### ISSUE THREAD

**Issue by mcdonnelldean** [nearform/vidi-dashboard#53]
Hey @thefoxis 

So today I need you to have a solid look over Vidi's current CSS and general layout and decide if it is something you want to work with, or if you want to bring in a pre-existing set of CSS and work from there.

I'm happy to follow your lead on this. We are building out an app as opposed to a site so I'm not sure if this changes the variables for your decision a bit.

We have some UI work around listing out each microservice and drilling into a sort of status overview page to come this week so whatever is decided needs to be something that won't swamp you in work.

I'm happy to iterate slowly on the move if needed.

**Comment by thefoxis** [comment]
Had a look at the code and here are some insight/proposals what could be done.

### Current state
* the design is pretty responsive
* visually okay
* CSS could be smaller (overall) and divided in modules
* there's a lot of repetition and randomness in terms of spacing, paddings, sizes, etc, should be more unified

### What could be done/improved
* deprecate icon font, replace with individual SVGs for icons (icon fonts are kind of a relict of the past these days, they have numerous accessibility issues plus the entire font file, or many, have to be downloaded instead of small vector files)
* make sure all visual assets are in SVG and optimised
* replace the current grid with flexboxgrid
* modularise and port to Stylus
* use variables
* refresh the look to match nodezoo
* use Google Fonts instead of local `@font-face`
* it'd be great to have the builds happening as the server runs, optionally with live reload (saves a lot of `⌘+R` and streamlines the workflow)

We could only refactor what's there but there are couple factors I'd think about when making a decision: getting into a new codebase always has a learning curve so I'd have to figure out how the layout works before making any changes to it. Obviously, that can be comparable to a rewrite, but I always find starting from scratch to be a better foundation for future collaborators. Does that sound alright? What should we do with the look (mentioned matching nodezoo a bit)? How can I get some dummy data in to visualise it properly? Let me know what you think @mcdonnelldean :)

**Comment by mcdonnelldean** [comment]
Brilliant stuff, @thefoxis 

If we are being fair, the current UI is a big pile of technical debt :D I'd like to remove this debt from play before we get to the point that it becomes a problem to deal with. With this in mind I think a 'rewrite' of the ui is the best option.

For this week's demo vidi needs to show.

- 3 Menu options
  - Live Overview
  - By Service
  - By Message Type

With each of these screens having very similar data to the Calibre screen you should be. I'll detail each of these screens in separate issues.

## Iteration focus
Lets focus on having the following items complete first

- Any necessary base work
- Login Screen
- Sidebar (items on menu can be fixed for now)
- Right Panel

Once these are done I have enough UI for Vidi and Concorda to get devs working on linking server work to components. At this point we can give do dummy data per panel and work on a panel by panel basis

### Accent Color
Both apps are related enough that we want to use the same overall UI and layouts for both Vidi and Concorda. With this in mind can he have an overarching accent color in each app? Navy / Blue for Vidi and say Green / lighter green for Concorda?

### Inspiration
Calibre is pretty much the closest example of what we are building I could give you, the context of what we are using it for is very different but it will look very similar to it overall. I'd like to see something in the spirit of it but keeping it all very light, like you did with NodeZoo.

**Comment by mcdonnelldean** [comment]
@thefoxis I'll add a new branch with some bits removed this evening so it will run stand-alone. I'll also add more detail for you to work from too :D

**Comment by mcdonnelldean** [comment]
Ok so I've opened a new branch `ui-redo` I unhooked everything so you can run npm run start and log in / log out without data flying all over the place. We are redoing that part so it's not useful to keep on.

When you log in you will get a sidebar and an empty 'Page' this is pretty much as far as we need to get to be functional again. I've added comments below that I think may help.

- Home is really overview, that is what info will be there, an overview of the system you are targeting

- The Home components owns it's sidebar, this means to add the other components for the /bymessage /byservice pages you need to add the sidebar to them. It's was due to my lack of positioning ability. If it makes more sense move this out that's fine.

- For now can you assume the shell component represents the page body? The actual markup will render inside two divs like, But if you add all your markup from the shell down when we get server side rendering up we can just drop the two divs and be semantically correct, rather than breaking components later.

```
<div id='app'>
  <div class='shell'>
    // add markup as if this was <body>
```

- The menu only needs three items on it, each corresponding to a page or route
  - / (Overview)
  - /byservice (By Service)
  - /bymessage (By Message)

- Each page can be blank save for a heading to match the name, we will add content after. 

- We have the concept of a profile, but they won't have profile images, you're free to place the logout and profile links wherever you feel best fits the design. /profile would be just another blank page, we intend to add settings here in a later iteration

- Each of the pages / (overview), /bymessage, /byservice will display a real time window of data over various charts and grids to the user. The current version does both service and message info on one page over 120s in real time. In the heading section of each of the above pages can we build in a drop down box so the person can set the window of time? The valid values are
  - 60s
  - 120s
  - 5min
  - 30min
  - 1hour
  - 1day

We will sync this across related pages so it behaves like a system wide setting on realtime pages. We may have other controls on the dead of each page too, keep it in mind.

I think that's everything. If you need anymore, just ping :D

**Comment by thefoxis** [comment]
Breaking down in to-do's:

- [ ] deprecate icon font, replace with individual SVGs for icon
- [ ] all visual assets should be in SVG and optimised
- [ ] replace the current grid with flexboxgrid
- [ ] modularise and port to Stylus
- [ ] use variables
- [ ] refresh the look to match Nodezoo
- [ ] use Google Fonts instead of local @font-face
- [ ] page: log in
- [ ] page: home

**Comment by mcdonnelldean** [comment]
@thefoxis Made some changes to page names put I hooked up all the routes and removed any unneeded components. Should be easier to work in now :D

**Comment by mcdonnelldean** [comment]
@thefoxis So I've committed a load of comments around the areas where styles or markup is decision based (like the sidebar toggle for instance). One important point is you need to delete the comments from the render methods otherwise they show up on the page (Damn you JSX Parser)

The key point is you shouldn't care where the state comes from or when it flips, this means you should be able to fake any state you need with a local variable and then have the devs hook up the state correctly.

Right now I have all the state for toggling the sidebar and causing a login error flowing down but if we need more we can add it.

I can also do a super simple 5 minute call when you get on later if you want me to run through it all. 

It's super important though that we make React work for the design. If you have to do something hacky to make the design work that's a problem we need to sort for you. You should always be able to use simple clean html / css with a bit of class or html swapping.

**Comment by thefoxis** [comment]
I didn't really have any major issues with React and syntax so far, just some minor reshuffling I've opened issues for :) 

I believe all other outstanding issues have been tackled for this milestone—please have a look and let me know if there's anything that should be taken care of my time on Monday. If not, I'll either work on `/profile` or also proceed with concorda.

**Comment by mcdonnelldean** [comment]
All looks perfect, both here and on Concorda. I'll close this now as that's the core work for this iteration done. Next will be to concorda for some minor styling and a color change :D Awesome stuff from you :+1:
