### ISSUE TITLE
Restructure the way icons are being served

### ISSUE THREAD

**Issue by thefoxis** [nearform/vidi-dashboard#55]
I think that previously the Font Awesome icon font was loaded somewhat dynamically in [boxheader.js](https://github.com/nearform/vidi-dashboard/blob/ui-redo/client/components/boxHeader.js#L12-L50). Unfortunately that implementation doesn't work with just using classes and background images as we do now, as it results in this for all the icons, despite the logo:

```
GET http://localhost:3000/img/icon-signin.svg 404 (Not Found)
```

It'd be great to have that working statically (just plain HTML syntax for including icons) with handling the change of sing in and sign out change. It doesn't have to be dynamically figuring out classes or anything like that, I think it's too complex for the interface needs. Unsure what's the aim of `boxheader` module but I'm sure we can make icons easily amendable and keep componentised header with icon + title if necessary.

Let me know if you have any questions about what I mean :) For now, because of the implementation mismatch, there are no icons displayed. #53

**Comment by mcdonnelldean** [comment]
@thefoxis Ok I have some changes incoming later on to sort this out. I now have your little square icons showing.

On the images. I've updated the paths in the icon stylesheet to use relative paths. There is some magic going on here. Basically we are using webpack to inline small images. This means webpack needs to know where the image was _before_ the dest folder was made. Since all of the stylus ends up in the root /css folder as one file the relative path for any stylesheet file is `../img`

The new styles now look like this:

```
background-image: url("../img/icon-menu.svg")
```

On the BoxHeader, this was a cludge component to help me have some sort of header for prototyping with. I've removed this and replaced all instances with the equivalent markup. This should allow you to do whatever you need with markup. Since it was purely stylistic there is no requirement to keep it.

I think this all unblocks you know, I'll ping here again when the commit is up.

**Comment by mcdonnelldean** [comment]
Closed via https://github.com/nearform/vidi-dashboard/commit/c3c2235e0fe5f4ababe1c64c30f72d0b0a33bc8d
