### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by mcdonnelldean** [nearform/vidi-dashboard#90]
It only needs to be added to the assets folder. The plumbing to serve it is missing. Once added assign back to me and I will update to serve correctly.

**Comment by thefoxis** [comment]
@mcdonnelldean — thought I could figure it out so I added the `copyfiles` and the route to assets in the config as well but it doesn't seem to work, maybe there's some minor difference in the setup because I see the file in the `*.html` but can't see it being requested. I'll let you set it up, thought could finish it off :sweat_smile:

**Comment by mcdonnelldean** [comment]
@thefoxis Awesome, this actually looks right. I'll drop the extra route in my next commit it's not needed. I had the exact same issue and then it started to work. I think the browser is caching it. Either way I'll be updating webpack soon so I can check it there. 

I'll go ahead an close as done. Super stuff :+1:
